#!/bin/sh
# Script file, called from urun, 
# that destroys the shared VM in which all the
# activatable services are running under JRMP,
# and removes the service's log files.

JDK_HOME=$1
JINI_HOME=$2
EXAMPLE_HOME=$3
HOSTNAME=$4
CODEBASE_PORT=$5

REGGIE_PERSIST_DIR="/var/tmp/jrmp-reggie-log"
MAHALO_PERSIST_DIR="/var/tmp/jrmp-mahalo-log"
FIDDLER_PERSIST_DIR="/var/tmp/jrmp-fiddler-log"
NORM_PERSIST_DIR="/var/tmp/jrmp-norm-log"
MERCURY_PERSIST_DIR="/var/tmp/jrmp-mercury-log"
OUTRIGGER_PERSIST_DIR="/var/tmp/jrmp-outrigger-log"

START_SERVICE="$JDK_HOME/bin/java \
-Djava.security.manager= \
-Djava.security.policy=$EXAMPLE_HOME/example/common/jrmp/policy/start-service.policy \
-Djava.util.logging.manager=com.sun.jini.logging.LogManager \
-Djava.util.logging.config.file=$EXAMPLE_HOME/example/common/logging/jini.logging \
-Dconfig=$EXAMPLE_HOME/example/common/jrmp/config/start-all-activatable.config \
-DserverHost=$HOSTNAME \
-DsharedVMLog=/tmp/jrmp-all-sharedvm \
-DcodebaseHost=$HOSTNAME \
-DcodebasePort=$CODEBASE_PORT \
-DjiniHome=$JINI_HOME \
-DappHome=$EXAMPLE_HOME \
-jar $JINI_HOME/lib/destroy.jar \
$EXAMPLE_HOME/example/common/jrmp/config/start-all-activatable.config"

echo "$START_SERVICE"
echo " "
$START_SERVICE

echo "rm -rf $REGGIE_PERSIST_DIR"
rm -rf $REGGIE_PERSIST_DIR
echo "rm -rf $MAHALO_PERSIST_DIR"
rm -rf $MAHALO_PERSIST_DIR
echo "rm -rf $FIDDLER_PERSIST_DIR"
rm -rf $FIDDLER_PERSIST_DIR
echo "rm -rf $NORM_PERSIST_DIR"
rm -rf $NORM_PERSIST_DIR
echo "rm -rf $MERCURY_PERSIST_DIR"
rm -rf $MERCURY_PERSIST_DIR
echo "rm -rf $OUTRIGGER_PERSIST_DIR"
rm -rf $OUTRIGGER_PERSIST_DIR
echo " "
