#!/bin/sh
# Script file, called from urun, 
# that stops the HTTPD server

JDK_HOME=$1
JINI_HOME=$2

PORT_ARG="-port $3"

STOP_HTTPD="$JDK_HOME/bin/java -jar $JINI_HOME/lib/tools.jar $PORT_ARG -stop"

echo "$STOP_HTTPD"
echo " "
$STOP_HTTPD

