#!/bin/sh
# Script file, called from urun, 
# that starts all services in
# nonactivatable mode, running under JERI

JDK_HOME=$1
JINI_HOME=$2
EXAMPLE_HOME=$3
HOSTNAME=$4
CODEBASE_PORT=$5
DEBUG=$6

START_SERVICE="$JDK_HOME/bin/java \
-Djava.security.manager= \
-Djava.security.policy=$EXAMPLE_HOME/example/common/jeri/policy/start-service.policy \
-Djava.util.logging.manager=com.sun.jini.logging.LogManager \
-Djava.util.logging.config.file=$EXAMPLE_HOME/example/common/logging/jini.logging \
-Dconfig=$EXAMPLE_HOME/example/common/jeri/config/start-all-nonactivatable.config \
-DserverHost=$HOSTNAME \
-DcodebaseHost=$HOSTNAME \
-DcodebasePort=$CODEBASE_PORT \
-DjiniHome=$JINI_HOME \
-DappHome=$EXAMPLE_HOME \
-Djava.security.debug=$DEBUG \
-jar $JINI_HOME/lib/start.jar \
$EXAMPLE_HOME/example/common/jeri/config/start-all-nonactivatable.config"

echo "$START_SERVICE"
echo " "
$START_SERVICE

