#!/bin/sh
# Script file, called from urun, 
# that starts Phoenix running under JERI

JDK_HOME=$1
JINI_HOME=$2
EXAMPLE_HOME=$3
HOSTNAME=$4
CODEBASE_PORT=$5
DEBUG=$6

PERSIST_DIR="/var/tmp/jeri-phoenix-log"

START_SERVICE="$JDK_HOME/bin/java \
-Djava.security.manager= \
-Djava.security.policy=$EXAMPLE_HOME/example/common/jeri/policy/start-service.policy \
-Djava.util.logging.manager=com.sun.jini.logging.LogManager \
-Djava.util.logging.config.file=$EXAMPLE_HOME/example/common/logging/phoenix.logging \
-Dconfig=$EXAMPLE_HOME/example/common/jeri/config/start-phoenix.config \
-DgroupConfig=$EXAMPLE_HOME/example/phoenix/jeri/config/phoenix-group.config \
-DserverHost=$HOSTNAME \
-DpersistDir=$PERSIST_DIR \
-DcodebaseHost=$HOSTNAME \
-DcodebasePort=$CODEBASE_PORT \
-DjiniHome=$JINI_HOME \
-DappHome=$EXAMPLE_HOME \
-Djava.security.debug=$DEBUG \
-jar $JINI_HOME/lib/start.jar \
$EXAMPLE_HOME/example/common/jeri/config/start-phoenix.config"


echo "$START_SERVICE"
echo " "
$START_SERVICE

