#!/bin/sh
# Script file, called from urun, 
# that stops Phoenix running under
# secure JERI/jsse, and removes all
# of Phoenix's log files.

JDK_HOME=$1
JINI_HOME=$2
EXAMPLE_HOME=$3
HOSTNAME=$4
CODEBASE_PORT=$5
DEBUG=$6
PHOENIX_MESSAGE_DIGEST=$7
JSK_MESSAGE_DIGEST=$8

PERSIST_DIR="/var/tmp/jsse-phoenix-log"

START_SERVICE="$JDK_HOME/bin/java \
-Djava.security.manager= \
-Djava.security.policy=$EXAMPLE_HOME/example/phoenix/jsse/policy/phoenix.policy \
-Djava.rmi.server.codebase="httpmd://$HOSTNAME:$CODEBASE_PORT/phoenix-dl.jar;sha=$PHOENIX_MESSAGE_DIGEST httpmd://$HOSTNAME:$CODEBASE_PORT/jsk-dl.jar;sha=$JSK_MESSAGE_DIGEST" \
-Djava.security.auth.login.config=$EXAMPLE_HOME/example/phoenix/jsse/login/phoenix.login \
-Djavax.net.ssl.trustStore=$EXAMPLE_HOME/example/common/jsse/truststore/jini-ca.truststore \
-Djava.protocol.handler.pkgs=net.jini.url \
-Djava.security.properties=$EXAMPLE_HOME/example/common/jsse/props/dynamic-policy.properties \
-Djava.util.logging.config.file=$EXAMPLE_HOME/example/common/logging/phoenix.logging \
-Dconfig=$EXAMPLE_HOME/example/phoenix/jsse/config/phoenix.config \
-DgroupConfig=$EXAMPLE_HOME/example/phoenix/jsse/config/phoenix-group.config \
-DserverHost=$HOSTNAME \
-DphoenixPort=2000 \
-DpersistDir=$PERSIST_DIR \
-DjiniHome=$JINI_HOME \
-DappHome=$EXAMPLE_HOME \
-Djava.security.debug=$DEBUG \
-jar $JINI_HOME/lib/phoenix.jar -stop \
$EXAMPLE_HOME/example/phoenix/jsse/config/phoenix.config"

echo "$START_SERVICE"
echo " "
$START_SERVICE
echo " "

echo "rm -rf $PERSIST_DIR"
rm -rf $PERSIST_DIR
echo " "
